apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
images:
- name: ghcr.io/argocon2022-workshop/demo-app
  newName: ghcr.io/wmgroot/demo-app
  newTag: 66ed627874da56f23abd5e343057a2fc92d26210
